#!/bin/sh

# ensure that multiple, simultaneous IOCs are not started by this user ID

MY_UID=`id -u`
IOC_PID="`/usr/bin/pgrep tmm\$ -u ${MY_UID}`"

if [ "" != "${IOC_PID}" ] ; then
  echo "tmm IOC is already running, won't start a new one, PID=${IOC_PID}"
  exit 1
fi

# start the IOC

../../bin/linux-arm/tmm st.cmd
